/*
-- Query: SELECT * FROM akcopema.movie
LIMIT 0, 1000

-- Date: 2016-04-07 15:31
*/
INSERT INTO `movie` (`MOVIE_ID`,`MOVIE_NAME`,`MOVIE_DIRECTOR`,`MOVIE_LEAD_ACTOR`,`MOVIE_RATING`,`MOVIE_DESCRIPTION`,`MOVIE_YEAR`,`MOVIE_RUNTIME`,`MOVIE_YOUTUBE`) VALUES (1,'Everest','Baltasar Kormákur',' Jason Clarke','PG-13','A climbing expedition on Mt. Everest is devastated by a severe snow storm.',2015,120,'<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/dOHS-mxn0RQ\" frameborder=\"0\" allowfullscreen></iframe>');
INSERT INTO `movie` (`MOVIE_ID`,`MOVIE_NAME`,`MOVIE_DIRECTOR`,`MOVIE_LEAD_ACTOR`,`MOVIE_RATING`,`MOVIE_DESCRIPTION`,`MOVIE_YEAR`,`MOVIE_RUNTIME`,`MOVIE_YOUTUBE`) VALUES (2,'Dawn of the Planet of the Apes','Matt Reeves',' Gary Oldman','PG-13','A growing nation of genetically evolved apes led by Caesar is threatened by a band of human survivors of the devastating virus unleashed a decade earlier.',2014,130,'<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/EcRIUU_QZiY\" frameborder=\"0\" allowfullscreen></iframe>');
INSERT INTO `movie` (`MOVIE_ID`,`MOVIE_NAME`,`MOVIE_DIRECTOR`,`MOVIE_LEAD_ACTOR`,`MOVIE_RATING`,`MOVIE_DESCRIPTION`,`MOVIE_YEAR`,`MOVIE_RUNTIME`,`MOVIE_YOUTUBE`) VALUES (3,'The Dark Knight','Christopher Nolan',' Christian Bale','PG-13','When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, the caped crusader must come to terms with one of the greatest psychological tests of his ability to fight injustice.',2008,150,'<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/EXeTwQWrcwY\" frameborder=\"0\" allowfullscreen></iframe>');
INSERT INTO `movie` (`MOVIE_ID`,`MOVIE_NAME`,`MOVIE_DIRECTOR`,`MOVIE_LEAD_ACTOR`,`MOVIE_RATING`,`MOVIE_DESCRIPTION`,`MOVIE_YEAR`,`MOVIE_RUNTIME`,`MOVIE_YOUTUBE`) VALUES (4,'Interstellar','Christopher Nolan','Matthew McConaughey','PG-13','A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',2014,170,'<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/0vxOhd4qlnA\" frameborder=\"0\" allowfullscreen></iframe>');
INSERT INTO `movie` (`MOVIE_ID`,`MOVIE_NAME`,`MOVIE_DIRECTOR`,`MOVIE_LEAD_ACTOR`,`MOVIE_RATING`,`MOVIE_DESCRIPTION`,`MOVIE_YEAR`,`MOVIE_RUNTIME`,`MOVIE_YOUTUBE`) VALUES (5,'The Bourne Identity',' Doug Liman','Matt Damon','PG-13','A man is picked up by a fishing boat, bullet-riddled and suffering from amnesia, before racing to elude assassins and regain his memory.',2002,120,'<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/FpKaB5dvQ4g\" frameborder=\"0\" allowfullscreen></iframe>');
