/*
-- Query: SELECT * FROM akcopema.movie_times
LIMIT 0, 1000

-- Date: 2016-04-07 15:32
*/
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (1,1);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (2,2);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (3,1);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (4,2);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (5,1);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (6,4);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (7,5);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (8,4);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (9,5);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (10,4);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (11,3);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (12,3);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (13,3);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (14,3);
INSERT INTO `movie_times` (`SHOWTIME_ID`,`MOVIE_ID`) VALUES (15,3);
