-- MySQL Script generated by MySQL Workbench
-- 03/05/16 11:21:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema akcopema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema akcopema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `akcopema` DEFAULT CHARACTER SET latin1 ;
USE `akcopema` ;

-- -----------------------------------------------------
-- Table `akcopema`.`movie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akcopema`.`movie` ;

CREATE TABLE IF NOT EXISTS `akcopema`.`movie` (
  `MOVIE_ID` INT(2) NOT NULL AUTO_INCREMENT,
  `MOVIE_NAME` TINYTEXT NOT NULL,
  `MOVIE_DIRECTOR` TINYTEXT NULL DEFAULT NULL,
  `MOVIE_LEAD_ACTOR` TINYTEXT NULL DEFAULT NULL,
  `MOVIE_RATING` TINYTEXT NULL DEFAULT NULL,
  `MOVIE_DESCRIPTION` MEDIUMTEXT NULL DEFAULT NULL,
  `MOVIE_YEAR` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`MOVIE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `akcopema`.`showroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akcopema`.`showroom` ;

CREATE TABLE IF NOT EXISTS `akcopema`.`showroom` (
  `SHOWROOM_ID` INT(2) NOT NULL,
  `SHOWROOM_DESC` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`SHOWROOM_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `akcopema`.`showtime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akcopema`.`showtime` ;

CREATE TABLE IF NOT EXISTS `akcopema`.`showtime` (
  `SHOWTIME_ID` INT(2) NOT NULL AUTO_INCREMENT,
  `SHOWROOM_ID` INT(2) NOT NULL,
  `TIME_SLOT` DATETIME NOT NULL,
  PRIMARY KEY (`SHOWROOM_ID`, `SHOWTIME_ID`),
  INDEX `SHOWROOM_ID` (`SHOWTIME_ID` ASC),
  CONSTRAINT `SHOWROOM_ID`
    FOREIGN KEY (`SHOWTIME_ID`)
    REFERENCES `akcopema`.`showroom` (`SHOWROOM_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `akcopema`.`movie_times`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akcopema`.`movie_times` ;

CREATE TABLE IF NOT EXISTS `akcopema`.`movie_times` (
  `SHOWTIME_ID` INT(2) NOT NULL,
  `MOVIE_ID` INT(2) NOT NULL,
  PRIMARY KEY (`SHOWTIME_ID`, `MOVIE_ID`),
  INDEX `MOVIE_ID_idx` (`MOVIE_ID` ASC),
  CONSTRAINT `MOVIE_ID`
    FOREIGN KEY (`MOVIE_ID`)
    REFERENCES `akcopema`.`movie` (`MOVIE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `SHOWTIME_ID`
    FOREIGN KEY (`SHOWTIME_ID`)
    REFERENCES `akcopema`.`showtime` (`SHOWTIME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `akcopema`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akcopema`.`user_account` ;

CREATE TABLE IF NOT EXISTS `akcopema`.`user_account` (
    `USER_ACCOUNT_ID` INT(2) NOT NULL AUTO_INCREMENT,
    `USER_PASSENCRYPT` TINYTEXT NOT NULL,
    `USER_FNAME` TINYTEXT NOT NULL,
    `USER_LNAME` TINYTEXT NOT NULL,
    `USER_STREETNUM` INT(11) NULL DEFAULT NULL,
    `USER_STREET` TINYTEXT NULL DEFAULT NULL,
    `USER_ZIP` INT(11) NULL DEFAULT NULL,
    PRIMARY KEY (`USER_ACCOUNT_ID`)
)  ENGINE=INNODB DEFAULT CHARACTER SET=LATIN1;


-- -----------------------------------------------------
-- Table `akcopema`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `akcopema`.`reservation` ;

CREATE TABLE IF NOT EXISTS `akcopema`.`reservation` (
  `RESERVATION_ID` INT(3) NOT NULL AUTO_INCREMENT,
  `USER_ACCOUNT_ID` INT(3) NOT NULL,
  `SHOWTIME_ID` INT(2) NOT NULL,
  `RESERVATION_TICKETNUM` INT(3) NOT NULL,
  PRIMARY KEY (`RESERVATION_ID`, `USER_ACCOUNT_ID`, `SHOWTIME_ID`),
  INDEX `USER_ACCOUNT_ID_idx` (`USER_ACCOUNT_ID` ASC),
  INDEX `SHOWTIME_ID_idx` (`SHOWTIME_ID` ASC),
  CONSTRAINT `FK_SHOWTIME_ID`
    FOREIGN KEY (`SHOWTIME_ID`)
    REFERENCES `akcopema`.`showtime` (`SHOWTIME_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `USER_ACCOUNT_ID`
    FOREIGN KEY (`USER_ACCOUNT_ID`)
    REFERENCES `akcopema`.`user_account` (`USER_ACCOUNT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
